[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; script-src * 'unsafe-inline' 'unsafe-eval' blob: data:; worker-src * blob: data:;"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/api/wfp"
  to = "/.netlify/functions/wfp"
  status = 200

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200

[[redirects]]
  from = "/api/hdx"
  to = "/.netlify/functions/hdx"
  status = 200

[[redirects]]
  from = "/api/ipc"
  to = "/.netlify/functions/ipc"
  status = 200
