[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:;"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/api/wfp"
  to = "/.netlify/functions/wfp"
  status = 200

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200
